use_frameworks!

platform :ios, '8.0'

target 'ZXDDemoLib_Example' do
  pod 'ZXDDemoLib', :path => '../'

  target 'ZXDDemoLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
