source 'https://github.com/githubxiangdong/ZXDDemoSpecs.git'

use_frameworks!

platform :ios, '9.0'

target 'ZXDDemoLib_Example' do
  pod 'ZXDDemoLib', :path => '../'
  
  target 'ZXDDemoLib_Tests' do
    inherit! :search_paths
    
    pod 'FBSnapshotTestCase'
  end
end
